#image: java:11
#image: openjdk:11
#image: gradle:alpine
image: gradle:5.6.2-jdk11

stages:
#  - build
  - test
  - deploy

#build:
#  stage: build
#  script: ./gradlew --build-cache assemble
#  cache:
#    key: "$CI_COMMIT_REF_NAME"
#    policy: push
#    paths:
#      - build
#      - .gradle

test:
  stage: test
  script:
    - gradle test
  artifacts:
    reports:
      junit: build/test-results/test/TEST-*.xml

#java:
#  stage: test
#  script:
#    - gradle test
#  artifacts:
#    reports:
#      junit: build/test-results/test/**/TEST-*.xml


deploy:
  stage: deploy
  image: ruby:2.3
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$APP_NAME --api-key=$API_KEY
  only:
    - master
